### ISSUE TITLE
Patch/Update behavior - No way to remove a sub field

### ISSUE THREAD

**Issue by lucabelluccini** [nicolaiarocci/eve#712] opened 2015-09-14 15:30 UTC
If I have a document and I apply some changes to the updates in the update callback on a sub object of it, some fields are not cleaned.

E.g.

Document: { 'field1': 'test', 'field2': { 'subfield1': 1, 'subfield2': 2 } }

Changes in the update item callback: { 'field2' : { 'subfield2': 22 } }

Result: { 'field1': 'test', 'field2': { 'subfield1': 1, 'subfield2': 22 } }

**Comment by nicolaiarocci** [comment] 2015-09-15 08:56
Yes this is the intended behavious.

 >Nested document updates are merged with the original contents, we don't overwrite the whole thing. See #519 for details.

[Source](https://github.com/nicolaiarocci/eve/blob/develop/eve/methods/patch.py#L253-L254)

You might want to use PUT instead.

**Closed by nicolaiarocci** 2015-09-15 08:56 UTC
